/* eslint-disable */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.
// Import Routes
import { Route as rootRoute } from './routes/__root';
import { Route as MyAccountImport } from './routes/myAccount';
import { Route as LoginImport } from './routes/login';
import { Route as CreateAccountImport } from './routes/createAccount';
import { Route as IndexImport } from './routes/index';
// Create/Update Routes
const MyAccountRoute = MyAccountImport.update({
    id: '/myAccount',
    path: '/myAccount',
    getParentRoute: () => rootRoute,
});
const LoginRoute = LoginImport.update({
    id: '/login',
    path: '/login',
    getParentRoute: () => rootRoute,
});
const CreateAccountRoute = CreateAccountImport.update({
    id: '/createAccount',
    path: '/createAccount',
    getParentRoute: () => rootRoute,
});
const IndexRoute = IndexImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => rootRoute,
});
const rootRouteChildren = {
    IndexRoute: IndexRoute,
    CreateAccountRoute: CreateAccountRoute,
    LoginRoute: LoginRoute,
    MyAccountRoute: MyAccountRoute,
};
export const routeTree = rootRoute
    ._addFileChildren(rootRouteChildren)
    ._addFileTypes();
/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/createAccount",
        "/login",
        "/myAccount"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/createAccount": {
      "filePath": "createAccount.tsx"
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/myAccount": {
      "filePath": "myAccount.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
